# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Q-DEV' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Q-DEV

end

# target 'Q-STAGING' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for Q-STAGING

# end

# target 'QuidWallet' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for QuidWallet

# end
