export const actions = {
    FETCHING_TOKEN_TRANSACTIONS: 'FETCHING_TOKEN_TRANSACTIONS',
    GOT_TOKEN_TRANSACTIONS: 'GOT_TOKEN_TRANSACTIONS',

    CREATE_ASSET_TRANSFERS: 'CREATE_ASSET_TRANSFERS',
    DELETE_ASSET_TRANSFER: 'DELETE__ASSET_TRANSFER',

    CREATE_PRICE_HISTORICAL: 'CREATE_PRICE_HISTORICAL',
    STOP_SPINNER: 'TRANSCTIONS_STOP_SPINNER'
};
