export const actions = {
    UPDATE_FCM_TOKEN: 'UPDATE_FCM_TOKEN',
    UPDATE_NOTIFICATION_IS_ON: 'UPDATE_NOTIFICATION_IS_ON',
    UPDATE_ADDRESS_NOTIFICATION_SETTING: 'UPDATE_ADDRESS_NOTIFICATION_SETTING',
    BULK_UPDATE_ADDRESSES_NOTIFICATION_SETTINGS: 'BULK_UPDATE_ADDRESSES_NOTIFICATION_SETTINGS',
    DEVICE_INITED_ON_NOTIFICATION_SERVER: 'DEVICE_INITED_ON_NOTIFICATION_SERVER'    
}
