export const actions = {
    FETCHING_ADDRESS_ASSETS: 'FETCHING_ADDRESS_ASSETS',
    GOT_ADDRESS_ASSETS: 'GOT_ADDRESS_ASSETS',
    GOT_NEW_TOKENS: 'GOT_NEW_TOKENS',
    GOT_TOKEN_BALANCE: 'GOT_TOKEN_BALANCE',
    
    ADD_WALLET: 'ADD_WALLET',
    UNLINK_WALLET: 'UNLINK_WALLET',

    SELECT_WALLET: 'SELECT_WALLET',
    STOP_REFRESHER: 'STOP_REFRESHER',

    TOGGLE_DISPAY_TOKEN_SETTING: 'TOGGLE_DISPAY_TOKEN_SETTING'    
};
